#!/usr/bin/env python3

import os
import http.client
import platform

if os.getuid():
    # fail if not root
    raise SystemExit("This script requires root to run. If you don't feel safe with that (as you should), feel free to first inspect the script at 'https://github.com/kevinshome/unixstamp', or manually install UNIXstamp yourself.")

if platform.system() == 'Windows':
    # windows support SOONR!
    raise SystemExit("Sorry, but this script only works on Linux, MacOS, and other UNIX-like systems right now, but should support Windows soon!")

# Interactive prompt
print("\033[1;37mWelcome to the interactive installer for UNIXstamp!")
prog_name = input(" \033[1;96mWhat would you like to the executable to be titled? (Default: 'unix'): \033[0m")
storage_location = input(" \033[1;96mWhere would you like the executable stored? (Default: '/usr/local/bin'): \033[0m")
if prog_name == '': prog_name = "unix"
if storage_location == '': storage_location = "/usr/local/bin"

# move into the exe's storage directory
os.chdir(storage_location)

# download UNIXstamp script from github
with open(prog_name, 'w') as f:
    j = http.client.HTTPSConnection("raw.githubusercontent.com", 443) # open connection
    j.request('GET', 'https://raw.githubusercontent.com/kevinshome/unixstamp/main/unixstamp') # make request
    res = j.getresponse() # store response
    lines = res.readlines() # store text
    j.close() # close connection
    for line in lines:
        f.write(line.decode('utf-8'))

os.chmod(prog_name, 0o555) # set UNIXscript permissions, equal to 'chmod 555' or R_X/R_X/R_X
print(f"UNIXstamp has been installed successfully!\nTo test it out, run: '{prog_name}'.")